#deploy twitter sentiment to master
- hosts: websites
  vars_files:
    - host_vars/web.yaml
  gather_facts: true

  roles:
    - role: backend-docker

- hosts: websites
  vars_files:
    - host_vars/web.yaml
  gather_facts: true

  roles:
    - role: frontend-docker